/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_isolated_nodes' is deprecated, use 'has_isolated_nodes' instead
  warnings.warn(out)
/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  warnings.warn(out)
Traceback (most recent call last):
  File "/scratch/midway3/cdonnat/gnumap/experiments/experiment_set_DGI.py", line 131, in <module>
    _, res = experiment(model='DGI', data=data,
TypeError: experiment() got an unexpected keyword argument 'model'
